command_timeout = 2000
[aws]
disabled=true

[character]
vicmd_symbol = "[V](bold green) "

[directory]
fish_style_pwd_dir_length=1
truncation_length = 2

[deno]
format = "via [🦕 $version](green bold) "

[time]
disabled=true
time_format = "🕙[ %T ]"

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[cmd_duration]
min_time = 500
format = "ran for [$duration](bold yellow)"

[nodejs]
disabled = true
